#!/bin/sh

set -e

mkdir -p ~/.ssh

chmod 700 ~/.ssh

echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

echo -e "${JIANMU_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa

set -x

chmod 600 ~/.ssh/id_rsa

ssh -p${JIANMU_SSH_PORT} ${JIANMU_SSH_USER}@${JIANMU_SSH_IP} "rm -rf ${JIANMU_REMOTE_FILE}"

scp -P${JIANMU_SSH_PORT} -r ${JIANMU_LOCAL_FILE} ${JIANMU_SSH_USER}@${JIANMU_SSH_IP}:${JIANMU_REMOTE_FILE}
