#!/bin/sh

set -e

mkdir -p ~/.ssh

chmod 700 ~/.ssh

echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

echo -e "${JIANMU_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa

chmod 600 ~/.ssh/id_rsa

set -x

ssh ${JIANMU_SSH_HOST} "${JIANMU_SSH_CMD}"
